mappings:
  - match: airflow.dag_processing.last_run.seconds_ago
    name: "airflow_dag_processing_last_run_seconds_ago"
    labels:
      dag_file: "$1"

  - match: airflow.dag_processing.processes
    name: "airflow_dag_processing_processes"

  - match: airflow.scheduler.tasks.running
    name: "airflow_scheduler_tasks_running"

  - match: airflow.scheduler.tasks.starving
    name: "airflow_scheduler_tasks_starving"

  - match: airflow.scheduler.tasks.executable
    name: "airflow_scheduler_tasks_executable"

  - match: airflow.executor.open_slots
    name: "airflow_executor_open_slots"

  - match: airflow.executor.queued_tasks
    name: "airflow_executor_queued_tasks"

  - match: airflow.executor.running_tasks
    name: "airflow_executor_running_tasks"

  - match: airflow.dag.*.*.duration
    name: "airflow_dag_task_duration"
    labels:
      dag_id: "$1"
      task_id: "$2"

  - match: airflow.dag_processing.import_errors
    name: "airflow_dag_processing_import_errors"

  - match: airflow.scheduler.critical_section_duration
    name: "airflow_scheduler_critical_section_duration"

  # 기본 매핑 (위 규칙에 없는 나머지)
  - match: airflow.*
    name: "airflow_$1"
